package org.exoplatform.support.cgvaldoise.page;

import org.apache.commons.lang3.StringUtils;

/**
 * Created by eXo Platform MEA on 13/06/14.
 *
 * @author <a href="mailto:mtrabelsi@exoplatform.com">Marwen Trabelsi</a>
 */
public class PageBuilder
{
  private final static String LINEBREAK = "\n";
  private final static String INDENTATION = "    ";
  private final static String CATALOG_PAGE_NAME = "<name>catalog${catalogPageId}</name>";
  private final static String CATALOG_PAGE_TITLE = "<title>Catalog${catalogPageId}</title>";
  private final static String CATALOG_PAGE_ID = "${catalogPageId}";

  private final static String SIMPLE_PAGE_NAME = "<name>simplepage${simplePageId}</name>";
  private final static String SIMPLE_PAGE_TITLE = "<title>Simple Page ${simplePageId}</title>";
  private final static String SIMPLE_PAGE_ID = "${simplePageId}";

  public static void buildCatalogPage(StringBuilder pageBuilder, String pageId)
  {
    pageBuilder
        .append("<page>").append(LINEBREAK)
        .append(INDENTATION).append(StringUtils.replace(CATALOG_PAGE_NAME, CATALOG_PAGE_ID, pageId))
        .append(LINEBREAK)
        .append(INDENTATION).append(StringUtils.replace(CATALOG_PAGE_TITLE, CATALOG_PAGE_ID, pageId))
        .append(LINEBREAK)
        .append(INDENTATION).append("<access-permissions>Everyone</access-permissions>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<edit-permission>*:/platform/administrators</edit-permission>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<portlet-application>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<portlet>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<application-ref>presentation</application-ref>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<portlet-ref>ContentListViewerPortlet</portlet-ref>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preferences>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>folderPath</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>repository:collaboration:/sites content/live/acme/categories/acme</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>nodeDrive</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>Managed Sites</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>orderType</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>ASC</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>formViewTemplatePath</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>/exo:ecm/views/templates/content-list-viewer/list/OneColumnCLVTemplate.gtmpl</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>paginatorTemplatePath</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>/exo:ecm/views/templates/content-list-viewer/paginators/UIPaginatorDefault.gtmpl</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>basePath</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>detail</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>itemsPerPage</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>6</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>showDateCreated</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>false</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>showReadmore</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>true</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>contextualFolder</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>contextualEnable</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>showScvWith</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>content-id</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<name>showClvBy</name>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<value>folder-id</value>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<read-only>false</read-only>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preference>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</preferences>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</portlet>")
        .append(LINEBREAK)
        .append(INDENTATION).append(StringUtils.replace(CATALOG_PAGE_TITLE, CATALOG_PAGE_ID, pageId))
        .append(LINEBREAK)
        .append(INDENTATION).append("<access-permissions>Everyone</access-permissions>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<show-info-bar>false</show-info-bar>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<show-application-state>false</show-application-state>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<show-application-mode>false</show-application-mode>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</portlet-application>")
        .append(LINEBREAK)
        .append("</page>");
  }

  public static void buildSimplePage(StringBuilder pageBuilder, String pageId)
  {
    pageBuilder
        .append("<page>").append(LINEBREAK)
        .append(INDENTATION).append(StringUtils.replace(SIMPLE_PAGE_NAME, SIMPLE_PAGE_ID, pageId))
        .append(LINEBREAK)
        .append(INDENTATION).append(StringUtils.replace(SIMPLE_PAGE_TITLE, SIMPLE_PAGE_ID, pageId))
        .append(LINEBREAK)
        .append(INDENTATION).append("<access-permissions>Everyone</access-permissions>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<edit-permission>*:/platform/administrators</edit-permission>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<portlet-application>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<portlet>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<application-ref>presentation</application-ref>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<portlet-ref>SingleContentViewer</portlet-ref>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<preferences>")
        .append(INDENTATION).append("</preferences>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</portlet>")
        .append(LINEBREAK)
        .append(INDENTATION).append(StringUtils.replace(SIMPLE_PAGE_TITLE, SIMPLE_PAGE_ID, pageId))
        .append(LINEBREAK)
        .append(INDENTATION).append("<access-permissions>Everyone</access-permissions>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<show-info-bar>false</show-info-bar>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<show-application-state>false</show-application-state>")
        .append(LINEBREAK)
        .append(INDENTATION).append("<show-application-mode>false</show-application-mode>")
        .append(LINEBREAK)
        .append(INDENTATION).append("</portlet-application>")
        .append(LINEBREAK)
        .append("</page>");
  }
}
